### ISSUE TITLE
Login credentials on demo home page are incorrect

### ISSUE THREAD

**Issue by stevepiercy** [kitconcept/kitconcept.voltodemo#5]
The login credentials at the bottom of the demo home page are incorrect:

user: test
password: test

They should be:

user: admin
password: admin

I assume this is something in the ZODB that requires someone who can update its content so that it remains after each nightly wipe.

**Comment by tisto** [comment]
@stevepiercy thanks for reporting! We will look into it.

**Comment by robdayz** [comment]
Somebody has changed the content of the page and modified the string admin to test, I think for joking purposes.
The system is cleared and reinstalled every night, but there was an error, and it wasn't working. Now the problem is solved.
We have checked that every night will be recreated with the default content, containing again the admin string in both sentences.
Seem that the problem is solved. 
Thanks for the info!
